# Logistic Regression | SciKit-Learn

## 1. Installing Dependancies - SHOULD be able to skip this

### Install Dependancies

In [3]:
%pip install pandas numpy scikit-learn torch matplotlib

Requirement already satisfied: pandas in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (3.1.0)
Requirement already satisfied: numpy in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (2.5.4)
Requirement already satisfied: scikit-learn in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (1.9.1)
Requirement already satisfied: torch in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (2.14.1)
Requirement already satisfied: matplotlib in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (3.11.2)
Requirement already satisfied: python-dateutil>=2.9.0 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from pandas) (3.0.0)
Requirement already satisfied: tzdata in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: scipy>=1.10.0 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: filelock in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from torch) (4.2.4)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from torch) (84.2.1)
Requirement already satisfied: sympy>=1.13.3 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from torch) (3.7)
Requirement already satisfied: jinja2 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from torch) (2026.9.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from matplotlib) (13.0.0)
Requirement already satisfied: pyparsing>=3 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: cloudpickle>=3.0 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.6 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\projects\a.school\machinelearning\a.finalproject\networktrafficclassifier\.venv\lib\site-packages (from jinja2->torch) (3.0.4)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### Validate if all Dependancies are Installed

In [2]:
import pandas as pd
import numpy as np
import sklearn
import torch
import matplotlib

print("All imports successful!")
print("PyTorch Version:", torch.__version__)

All imports successful!
PyTorch Version: 2.14.1+cpu

## 2. Explore the Dataset

In [ ]:
import pandas as pd
# df stands for DataFrame (a table full of the cvs data)
df = pd.read_csv("Dataset/Benign Traffic.csv")
df.head()

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Total Fwd Packet,Total Bwd packets,...,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Attack Name,Label
0,34.173.20.6-192.168.137.234-443-58644-6,34.173.20.6,443,192.168.137.234,58644,6,14/09/2023 09:24:26 AM,14746364,6,0,...,0.0,0.0,0.0,0.0,14681116.0,0.000000,14681116.0,14681116.0,Benign Traffic,0
1,34.173.20.6-192.168.137.234-443-58646-6,34.173.20.6,443,192.168.137.234,58646,6,14/09/2023 09:24:41 AM,60102110,18,0,...,219123.0,0.0,219123.0,219123.0,14957706.0,190543.248665,15061923.0,14672051.0,Benign Traffic,0
2,52.40.210.103-192.168.137.40-18665-60378-6,52.40.210.103,18665,192.168.137.40,60378,6,14/09/2023 09:24:14 AM,90106769,9,0,...,582529.0,0.0,582529.0,582529.0,29841412.0,319090.538141,30049066.0,29473997.0,Benign Traffic,0
3,10.0.0.3-10.0.0.254-44505-1883-6,10.0.0.3,44505,10.0.0.254,1883,6,14/09/2023 09:24:15 AM,119998980,123,123,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign Traffic,0
4,10.0.0.7-10.0.0.254-45727-1883-6,10.0.0.7,45727,10.0.0.254,1883,6,14/09/2023 09:24:15 AM,119998539,123,123,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign Traffic,0

In [7]:
df.shape

(32620, 85)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32620 entries, 0 to 32619
Data columns (total 85 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Flow ID                     32620 non-null  str
 1   Src IP                      32620 non-null  str
 2   Src Port                    32620 non-null  int64
 3   Dst IP                      32620 non-null  str
 4   Dst Port                    32620 non-null  int64
 5   Protocol                    32620 non-null  int64
 6   Timestamp                   32620 non-null  str
 7   Flow Duration               32620 non-null  int64
 8   Total Fwd Packet            32620 non-null  int64
 9   Total Bwd packets           32620 non-null  int64
 10  Total Length of Fwd Packet  32620 non-null  float64
 11  Total Length of Bwd Packet  32620 non-null  float64
 12  Fwd Packet Length Max       32620 non-null  float64
 13  Fwd Packet Length Min       32620 non-null  float64
 14  Fwd Packet Length Mean      32620 non-null  float64
 15  Fwd Packet Length Std       32620 non-null  float64
 16  Bwd Packet Length Max       32620 non-null  float64
 17  Bwd Packet Length Min       32620 non-null  float64
 18  Bwd Packet Length Mean      32620 non-null  float64
 19  Bwd Packet Length Std       32620 non-null  float64
 20  Flow Bytes/s                32620 non-null  float64
 21  Flow Packets/s              32620 non-null  float64
 22  Flow IAT Mean               32620 non-null  float64
 23  Flow IAT Std                32620 non-null  float64
 24  Flow IAT Max                32620 non-null  float64
 25  Flow IAT Min                32620 non-null  float64
 26  Fwd IAT Total               32620 non-null  float64
 27  Fwd IAT Mean                32620 non-null  float64
 28  Fwd IAT Std                 32620 non-null  float64
 29  Fwd IAT Max                 32620 non-null  float64
 30  Fwd IAT Min                 32620 non-null  float64
 31  Bwd IAT Total               32620 non-null  float64
 32  Bwd IAT Mean                32620 non-null  float64
 33  Bwd IAT Std                 32620 non-null  float64
 34  Bwd IAT Max                 32620 non-null  float64
 35  Bwd IAT Min                 32620 non-null  float64
 36  Fwd PSH Flags               32620 non-null  int64
 37  Bwd PSH Flags               32620 non-null  int64
 38  Fwd URG Flags               32620 non-null  int64
 39  Bwd URG Flags               32620 non-null  int64
 40  Fwd Header Length           32620 non-null  int64
 41  Bwd Header Length           32620 non-null  int64
 42  Fwd Packets/s               32620 non-null  float64
 43  Bwd Packets/s               32620 non-null  float64
 44  Packet Length Min           32620 non-null  float64
 45  Packet Length Max           32620 non-null  float64
 46  Packet Length Mean          32620 non-null  float64
 47  Packet Length Std           32620 non-null  float64
 48  Packet Length Variance      32620 non-null  float64
 49  FIN Flag Count              32620 non-null  int64
 50  SYN Flag Count              32620 non-null  int64
 51  RST Flag Count              32620 non-null  int64
 52  PSH Flag Count              32620 non-null  int64
 53  ACK Flag Count              32620 non-null  int64
 54  URG Flag Count              32620 non-null  int64
 55  CWR Flag Count              32620 non-null  int64
 56  ECE Flag Count              32620 non-null  int64
 57  Down/Up Ratio               32620 non-null  float64
 58  Average Packet Size         32620 non-null  float64
 59  Fwd Segment Size Avg        32620 non-null  float64
 60  Bwd Segment Size Avg        32620 non-null  float64
 61  Fwd Bytes/Bulk Avg          32620 non-null  int64
 62  Fwd Packet/Bulk Avg         32620 non-null  int64
 63  Fwd Bulk Rate Avg           32620 non-null  int64
 64  Bwd Bytes/Bulk Avg          32620 non-null  int64
 65  Bwd Packet/Bulk Avg         32620 non-null  int64
 66  Bwd Bulk Rate Avg           32620 non-null  int64
 67  Subflow Fwd Packets         32620 non-null  int64
 68  Subflow Fwd Bytes           32620 non-null  int64
 69  Subflow Bwd Packets         32620 non-null  int64
 70  Subflow Bwd Bytes           32620 non-null  int64
 71  FWD Init Win Bytes          32620 non-null  int64
 72  Bwd Init Win Bytes          32620 non-null  int64
 73  Fwd Act Data Pkts           32620 non-null  int64
 74  Fwd Seg Size Min            32620 non-null  int64
 75  Active Mean                 32620 non-null  float64
 76  Active Std                  32620 non-null  float64
 77  Active Max                  32620 non-null  float64
 78  Active Min                  32620 non-null  float64
 79  Idle Mean                   32620 non-null  float64
 80  Idle Std                    32620 non-null  float64
 81  Idle Max                    32620 non-null  float64
 82  Idle Min                    32620 non-null  float64
 83  Attack Name                 32620 non-null  str
 84  Label                       32620 non-null  int64
dtypes: float64(45), int64(35), str(5)
memory usage: 21.2 MB

In [9]:
df["Attack Name"].value_counts()

Attack Name
Benign Traffic    32620
Name: count, dtype: int64

In [38]:
# pd.set_option("display.max_columns", None)
# df.dtypes

df.columns.tolist()

# for column, dtype in df.dtypes.items():
#     print(f"{column}: {dtype}")

['Flow ID',
 'Src IP',
 'Src Port',
 'Dst IP',
 'Dst Port',
 'Protocol',
 'Timestamp',
 'Flow Duration',
 'Total Fwd Packet',
 'Total Bwd packets',
 'Total Length of Fwd Packet',
 'Total Length of Bwd Packet',
 'Fwd Packet Length Max',
 'Fwd Packet Length Min',
 'Fwd Packet Length Mean',
 'Fwd Packet Length Std',
 'Bwd Packet Length Max',
 'Bwd Packet Length Min',
 'Bwd Packet Length Mean',
 'Bwd Packet Length Std',
 'Flow Bytes/s',
 'Flow Packets/s',
 'Flow IAT Mean',
 'Flow IAT Std',
 'Flow IAT Max',
 'Flow IAT Min',
 'Fwd IAT Total',
 'Fwd IAT Mean',
 'Fwd IAT Std',
 'Fwd IAT Max',
 'Fwd IAT Min',
 'Bwd IAT Total',
 'Bwd IAT Mean',
 'Bwd IAT Std',
 'Bwd IAT Max',
 'Bwd IAT Min',
 'Fwd PSH Flags',
 'Bwd PSH Flags',
 'Fwd URG Flags',
 'Bwd URG Flags',
 'Fwd Header Length',
 'Bwd Header Length',
 'Fwd Packets/s',
 'Bwd Packets/s',
 'Packet Length Min',
 'Packet Length Max',
 'Packet Length Mean',
 'Packet Length Std',
 'Packet Length Variance',
 'FIN Flag Count',
 'SYN Flag Count',
 'RST Flag Count',
 'PSH Flag Count',
 'ACK Flag Count',
 'URG Flag Count',
 'CWR Flag Count',
 'ECE Flag Count',
 'Down/Up Ratio',
 'Average Packet Size',
 'Fwd Segment Size Avg',
 'Bwd Segment Size Avg',
 'Fwd Bytes/Bulk Avg',
 'Fwd Packet/Bulk Avg',
 'Fwd Bulk Rate Avg',
 'Bwd Bytes/Bulk Avg',
 'Bwd Packet/Bulk Avg',
 'Bwd Bulk Rate Avg',
 'Subflow Fwd Packets',
 'Subflow Fwd Bytes',
 'Subflow Bwd Packets',
 'Subflow Bwd Bytes',
 'FWD Init Win Bytes',
 'Bwd Init Win Bytes',
 'Fwd Act Data Pkts',
 'Fwd Seg Size Min',
 'Active Mean',
 'Active Std',
 'Active Max',
 'Active Min',
 'Idle Mean',
 'Idle Std',
 'Idle Max',
 'Idle Min',
 'Attack Name',
 'Label']

In [15]:
df.info(show_counts=True, verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 32620 entries, 0 to 32619
Data columns (total 85 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Flow ID                     32620 non-null  str
 1   Src IP                      32620 non-null  str
 2   Src Port                    32620 non-null  int64
 3   Dst IP                      32620 non-null  str
 4   Dst Port                    32620 non-null  int64
 5   Protocol                    32620 non-null  int64
 6   Timestamp                   32620 non-null  str
 7   Flow Duration               32620 non-null  int64
 8   Total Fwd Packet            32620 non-null  int64
 9   Total Bwd packets           32620 non-null  int64
 10  Total Length of Fwd Packet  32620 non-null  float64
 11  Total Length of Bwd Packet  32620 non-null  float64
 12  Fwd Packet Length Max       32620 non-null  float64
 13  Fwd Packet Length Min       32620 non-null  float64
 14  Fwd Packet Length Mean      32620 non-null  float64
 15  Fwd Packet Length Std       32620 non-null  float64
 16  Bwd Packet Length Max       32620 non-null  float64
 17  Bwd Packet Length Min       32620 non-null  float64
 18  Bwd Packet Length Mean      32620 non-null  float64
 19  Bwd Packet Length Std       32620 non-null  float64
 20  Flow Bytes/s                32620 non-null  float64
 21  Flow Packets/s              32620 non-null  float64
 22  Flow IAT Mean               32620 non-null  float64
 23  Flow IAT Std                32620 non-null  float64
 24  Flow IAT Max                32620 non-null  float64
 25  Flow IAT Min                32620 non-null  float64
 26  Fwd IAT Total               32620 non-null  float64
 27  Fwd IAT Mean                32620 non-null  float64
 28  Fwd IAT Std                 32620 non-null  float64
 29  Fwd IAT Max                 32620 non-null  float64
 30  Fwd IAT Min                 32620 non-null  float64
 31  Bwd IAT Total               32620 non-null  float64
 32  Bwd IAT Mean                32620 non-null  float64
 33  Bwd IAT Std                 32620 non-null  float64
 34  Bwd IAT Max                 32620 non-null  float64
 35  Bwd IAT Min                 32620 non-null  float64
 36  Fwd PSH Flags               32620 non-null  int64
 37  Bwd PSH Flags               32620 non-null  int64
 38  Fwd URG Flags               32620 non-null  int64
 39  Bwd URG Flags               32620 non-null  int64
 40  Fwd Header Length           32620 non-null  int64
 41  Bwd Header Length           32620 non-null  int64
 42  Fwd Packets/s               32620 non-null  float64
 43  Bwd Packets/s               32620 non-null  float64
 44  Packet Length Min           32620 non-null  float64
 45  Packet Length Max           32620 non-null  float64
 46  Packet Length Mean          32620 non-null  float64
 47  Packet Length Std           32620 non-null  float64
 48  Packet Length Variance      32620 non-null  float64
 49  FIN Flag Count              32620 non-null  int64
 50  SYN Flag Count              32620 non-null  int64
 51  RST Flag Count              32620 non-null  int64
 52  PSH Flag Count              32620 non-null  int64
 53  ACK Flag Count              32620 non-null  int64
 54  URG Flag Count              32620 non-null  int64
 55  CWR Flag Count              32620 non-null  int64
 56  ECE Flag Count              32620 non-null  int64
 57  Down/Up Ratio               32620 non-null  float64
 58  Average Packet Size         32620 non-null  float64
 59  Fwd Segment Size Avg        32620 non-null  float64
 60  Bwd Segment Size Avg        32620 non-null  float64
 61  Fwd Bytes/Bulk Avg          32620 non-null  int64
 62  Fwd Packet/Bulk Avg         32620 non-null  int64
 63  Fwd Bulk Rate Avg           32620 non-null  int64
 64  Bwd Bytes/Bulk Avg          32620 non-null  int64
 65  Bwd Packet/Bulk Avg         32620 non-null  int64
 66  Bwd Bulk Rate Avg           32620 non-null  int64
 67  Subflow Fwd Packets         32620 non-null  int64
 68  Subflow Fwd Bytes           32620 non-null  int64
 69  Subflow Bwd Packets         32620 non-null  int64
 70  Subflow Bwd Bytes           32620 non-null  int64
 71  FWD Init Win Bytes          32620 non-null  int64
 72  Bwd Init Win Bytes          32620 non-null  int64
 73  Fwd Act Data Pkts           32620 non-null  int64
 74  Fwd Seg Size Min            32620 non-null  int64
 75  Active Mean                 32620 non-null  float64
 76  Active Std                  32620 non-null  float64
 77  Active Max                  32620 non-null  float64
 78  Active Min                  32620 non-null  float64
 79  Idle Mean                   32620 non-null  float64
 80  Idle Std                    32620 non-null  float64
 81  Idle Max                    32620 non-null  float64
 82  Idle Min                    32620 non-null  float64
 83  Attack Name                 32620 non-null  str
 84  Label                       32620 non-null  int64
dtypes: float64(45), int64(35), str(5)
memory usage: 21.2 MB

### Check for Null Values

In [28]:
# Displays the count of null values for each column
# df.isnull().sum()
# Displayes any columns that have null values | If empty, then no null values
df.isnull().sum()[lambda x: x > 0]

Series([], dtype: int64)

In [49]:
# Displays each attack name listed in under the Attack Name feature, and its count
df["Attack Name"].value_counts(dropna=False)

Attack Name
Benign Traffic    32620
Name: count, dtype: int64

In [50]:
# Displays the label listed under the Label feature, how many times each appeared
df["Label"].value_counts(dropna=False)

Label
0    32620
Name: count, dtype: int64

### Detecting Duplicate Rows

In [ ]:
# Count of Duplicate Rows
df.duplicated().sum()

np.int64(14)

In [46]:
duplicates = df[df.duplicated(keep=False)]
# duplicates
duplicates.head()

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Packet Length Min,Packet Length Max,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWR Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Fwd Segment Size Avg,Bwd Segment Size Avg,Fwd Bytes/Bulk Avg,Fwd Packet/Bulk Avg,Fwd Bulk Rate Avg,Bwd Bytes/Bulk Avg,Bwd Packet/Bulk Avg,Bwd Bulk Rate Avg,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,FWD Init Win Bytes,Bwd Init Win Bytes,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Attack Name,Label
5112,54.205.44.26-192.168.137.127-443-43832-6,54.205.44.26,443,192.168.137.127,43832,6,13/09/2023 11:27:21 AM,2,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000e+06,2.0,0.0,2.0,2.0,2.0,2.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,40,0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,2,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign Traffic,0
5113,54.205.44.26-192.168.137.127-443-43832-6,54.205.44.26,443,192.168.137.127,43832,6,13/09/2023 11:27:21 AM,2,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000e+06,2.0,0.0,2.0,2.0,2.0,2.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,40,0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,2,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign Traffic,0
8254,142.251.41.36-192.168.137.210-443-36890-6,142.251.41.36,443,192.168.137.210,36890,6,13/09/2023 01:27:41 PM,0,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22614.434597,7.470896e+03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,40,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,2,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign Traffic,0
8255,142.251.41.36-192.168.137.210-443-36890-6,142.251.41.36,443,192.168.137.210,36890,6,13/09/2023 01:27:41 PM,1,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,2.000000e+06,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,40,0,2000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,2,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign Traffic,0
8256,142.251.41.36-192.168.137.210-443-36890-6,142.251.41.36,443,192.168.137.210,36890,6,13/09/2023 01:27:41 PM,1,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,2.000000e+06,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,40,0,2000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,2,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign Traffic,0

In [45]:
df.drop_duplicates().shape
# df.shape

(32606, 85)

In [ ]:
duplicates = df[df.duplicated()]
print(duplicates.shape)

(14, 85)

In [51]:
import numpy as np

numeric_df = df.select_dtypes(include="number")

print("Infinite values:", np.isinf(numeric_df).sum().sum())
print("Constant columns:", (numeric_df.nunique() <= 1).sum())

Infinite values: 0
Constant columns: 9

In [52]:
constant_columns = numeric_df.columns[numeric_df.nunique() <= 1]

for column in constant_columns:
    print(f"{column}: {df[column].iloc[0]}")

Protocol: 6
Bwd PSH Flags: 0
Fwd URG Flags: 0
Bwd URG Flags: 0
URG Flag Count: 0
Fwd Bytes/Bulk Avg: 0
Fwd Packet/Bulk Avg: 0
Fwd Bulk Rate Avg: 0
Label: 0

### Check access to all CSVs in Database

In [53]:
from pathlib import Path
import pandas as pd

dataset_path = Path("Dataset")
csv_files = sorted(dataset_path.glob("*.csv"))

print("Number of CSV files:", len(csv_files))

for file in csv_files:
    print(file.name)

Number of CSV files: 15
Benign Traffic.csv
DDoS ICMP Flood.csv
DDoS UDP Flood.csv
DoS ICMP Flood.csv
DoS TCP Flood.csv
DoS UDP Flood.csv
MITM ARP Spoofing.csv
MQTT DDoS Publish Flood.csv
MQTT DoS Connect Flood.csv
MQTT DoS Publish Flood.csv
MQTT Malformed.csv
Recon OS Scan.csv
Recon Ping Sweep.csv
Recon Port Scan.csv
Recon Vulnerability Scan.csv

### Load all CSV files from Dataset

In [54]:
dataframes = []

for file in csv_files:
    temp_df = pd.read_csv(file)
    temp_df["Source File"] = file.stem
    dataframes.append(temp_df)

df_all = pd.concat(dataframes, ignore_index=True)

print("Combined shape:", df_all.shape)

Combined shape: (3385313, 86)

In [55]:
df_all["Attack Name"].value_counts()

Attack Name
DoS TCP Flood               2106916
Recon Port Scan              485522
MQTT DDoS Publish Flood      413913
MQTT DoS Connect Flood       238031
Recon OS Scan                 85317
Benign Traffic                32620
Recon Vulnerability Scan       8321
DoS UDP Flood                  3115
DDoS UDP Flood                 2576
DDoS ICMP Flood                2552
MQTT Malformed                 2246
DoS ICMP Flood                 2107
MITM ARP Spoofing              1053
MQTT DoS Publish Flood          953
Recon Ping Sweep                 71
Name: count, dtype: int64

In [ ]:
# 1 = Some type of Attack
# 0 = Benign Traffic
# Displays the count of attack data and benign data
df_all["Label"].value_counts()

Label
1    3352693
0      32620
Name: count, dtype: int64

In [ ]:
# Prints out the count of null values in the combined Dataset
missing = df_all.isnull().sum()
print(missing[missing > 0].sort_values(ascending=False))

Series([], dtype: int64)

In [ ]:
# Check for positive and negative infinity values
numeric_all = df_all.select_dtypes(include="number")

infinite_counts = np.isinf(numeric_all).sum()
print(infinite_counts[infinite_counts > 0].sort_values(ascending=False))

Series([], dtype: int64)

In [59]:
# Prints out the duplicate count
print("Exact duplicate rows:", df_all.duplicated().sum())

Exact duplicate rows: 109180

In [60]:
print(
    "Duplicates across original columns:",
    df_all.drop(columns="Source File").duplicated().sum()
)

Duplicates across original columns: 109180

In [61]:
original_columns = df_all.columns.drop("Source File")

cross_file_duplicates = (
    df_all.groupby(list(original_columns), dropna=False)["Source File"]
    .nunique()
)

print(
    "Duplicate row groups appearing in multiple files:",
    (cross_file_duplicates > 1).sum()
)

Duplicate row groups appearing in multiple files: 0